version: '3.8'
services:
  open-friendly-net-detection-server:
    image: apfelwurm/open-friendly-net-detection-server:latest
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./certs:/app/certs:ro
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "32125:32125/udp"
