name: build-server-image

on:
  push:
    branches: [ main, dev ]
  # pull_request:
  #   branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Determine tag
        id: tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then echo "tag=latest" >> $GITHUB_OUTPUT; elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then echo "tag=beta" >> $GITHUB_OUTPUT; else echo "tag=pr-${{ github.run_number }}" >> $GITHUB_OUTPUT; fi
      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3.5.0
        with:
          username: apfelwurm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./linux.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: apfelwurm/${{ github.event.repository.name }}:${{ steps.tag.outputs.tag }}
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            SOURCE_COMMIT=${{ github.sha }}
